services:
  db:
    image: postgres:15
    container_name: gestion_actividades_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gestion_actividades_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - gestion_net

volumes:
  pgdata:

networks:
  gestion_net:
    driver: bridge
